---
title: "e-Rum2020 Program"
author: "e-Rum2020 Organizing Committee"
date: "`r Sys.time()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    split_by: section
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Index {-}

- [Book of abstracts for accepted contributions](erum2020-contributed-program.html)

- [Detailed program schedule booklet](http://2020.erum.io/wp-content/uploads/2020/06/program_brochure_v5_20200617.pdf)

- [Conference materials](https://github.com/Milano-R/erum2020program#conference-materials) (collected in a [GitHub](https://github.com/Milano-R/erum2020program#conference-materials) repository)


# eRum2020 Contributed Program

Overview of accepted contributions organized by session type.

```{r, echo = FALSE, results = 'asis', warning = FALSE}
contributions <- jsonlite::read_json(
  file.path("data", "erum2020_confirmed_program.json"), 
  simplifyVector = TRUE
)
session_types <- unique(contributions$session_type)
for (session_type in session_types) {
  cat(knitr::knit_child(
    file.path("children", "session_type.Rmd"),
    quiet = TRUE
  ))
}
```
